"""empty message

Revision ID: f740c1da6d6c
Revises: ca8287ceadd4
Create Date: 2016-10-22 13:36:34.643927

"""

# revision identifiers, used by Alembic.
revision = 'f740c1da6d6c'
down_revision = 'ca8287ceadd4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('participante',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('votes', sa.Integer(), nullable=True),
    sa.Column('upload', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('participante')
    ### end Alembic commands ###
