"""empty message

Revision ID: f74a2de1d757
Revises: f740c1da6d6c
Create Date: 2016-10-30 12:28:22.987860

"""

# revision identifiers, used by Alembic.
revision = 'f74a2de1d757'
down_revision = 'f740c1da6d6c'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from sqlalchemy_utils import ChoiceType
from models import User



def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('role', sqlalchemy_utils.types.choice.ChoiceType(User.TYPES), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'role')
    ### end Alembic commands ###
